config/routes.rb
Rails.application.routes.draw do

  resources :user, only: [:update, :destroy]

	resources :posts do
		resources :comments, only: [:create, :destroy]
	end

	get 'dashboard', to: 'pages#dashboard'

	devise_for :users, controllers: {
		sessions: 'users/sessions',
		registrations: 'users/registrations'
	}

	root 'posts#index'
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/dashboard.html.erb
<div class="row">
  <div class="col-md-6">
    <table class="table table-bordered">
      <thead>

          <tr>
            <th><p>name</p></th>


            <th><p>Change Rol</p></th>

            <th><p>Final Rol</p></th>
            <th> <p>Options</p> </th>
          </tr>

      </thead>
      <tbody>
          <%  @users.each do |user| %>
          <tr>
            <td>
              <%= user.name %>
            </td>


            <td>
              <div class="form-group">
                <label for="sel1"><%= form_with url: user_path(user), method: "patch" do |user_form| %></label>
                <%= select_tag(:role, options_for_select([['admin', 'admin'] , ['visit', 'visit']])) %>
                <%= user_form.submit %>
                <% end %>

              </div>

            </td>
            <td>
              <%= user.role %>
            </td>
            <td>
              <%= link_to 'Eliminar', user_path(user), method: :delete, data: { confirm: 'Estás seguro que deseas eliminar el Usuario?' }, class: 'btn btn-sm btn-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'Volver', posts_path, class: 'btn btn-default' %>
  </div>
</div>